### ISSUE TITLE
Examples Index + Roadmap

### ISSUE THREAD

**Issue by lawcho** [lawcho/rpphp#1]
### Quick Start Examples
* [x] Minimal LED blink [led_blink1]
* [x] Non-LED Output [count_binary, count_7seg]
* [x] Input [relay]
* [x] Misc. Board-only programs [led_blink_slower, led_pwm1]

### How to implement IO style XXX
* [x] Haskell-style IO monad [led_blink_3]
* [ ] Gloss-style `play` function

### Alternatives to bit-banging
* [ ] Application-specific 3rd-party C libraries
* [x] On-chip specialized hardware (e.g. PWM/UART/SPI/I2C/USB) [led_pwm2]
* [ ] On-chip PIO hardware
